/*
	File: fn_setupTextures.sqf
	Author: ThirtySeven
	(setupTextures example by KiloSwiss on Nitrado Forums)
	
	Description:
	Lädt die Texturen beim beitritt des Spielers
*/
private ["_tempPlakat"];
[] spawn{
	_tempPlakat = "Land_Billboard_F" createVehicleLocal (player modelToWorld [0,0,0]);
	_tempPlakat attachTo[player,[0,0.0,0]];
	_tempPlakat allowDamage false;
	_tempPlakat hideObject true;
	_tempPlakat setDir 360;
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ziv_offroad_Getarnt.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ziv_offroad_Gay.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ziv_offroad.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ziv_hummingbird_Voll_Getarnt.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\zamak_weed_back.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\zamak_weed.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\werbung.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Werber3.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Werber2.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\van_kh_f.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\van_kh.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Van_gruen.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\uniform_FBI.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\uniform_DEA.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ThirtySeven_Werbung.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\swat_hunter.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_sek.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_security.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_pro.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_Monster_energy_block.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_medik.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_makaveli.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\suv_bmw.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\sun.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\sport.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\sman.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\riffelblech.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\redgull_hatchback_sport.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\recruit_uniform_rangemaster.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\rebell_hunter2.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\rebell_hunter.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\rally.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Quad.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Puma_Abklatsch.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\POR.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\polizei_uni.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\polizei_strider_ausbilder.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\polizei_strider.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\policehq.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\policeHB_Autobahn.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\policeHB.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_suv_autobahn.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_suv.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Police_Sea_Uniform_co.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_recruit_uniform.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_offroad_hamburg.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_Officer.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_hummingbird.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_hellcats.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_heli_ausbilder.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_heli.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\police_01.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\pokemon.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\orca_notarzt.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\oil.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\offroader.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\offroad_Rockstar_energy_rot_gelb.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\offroad_notarzt.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\offroad_Black-white_stickerbomb.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\offroad_badmobil.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\offroad_adac3.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Notarzt_Hummingbird.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Notarzt.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\NODDY.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\newoffroad.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\My_Pony.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\monsterenergy_off.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\med_uniform.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\med_suv.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\med_orca.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\med_offroad.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\med_hummingbird.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\MECH.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_red_front.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_red_back.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Ifrit_Polizei4_hinten.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Ifrit_Polizei4_Front.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_lion_front.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_lion_back.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_grey_front.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_grey_back.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_forest_front.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ifrit_forest_back.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\hunter_back.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\hemtt_adac.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Hello_Kitty.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\heli_Police.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\hatchbackv2.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\hatchbackv1.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\hatchback_sport_ken_block.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\hatchback_badmobil.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ghost_hatchback_sport.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ganja.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Fire_hatchback.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ferrari_suv.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\ferrari.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\fbi_hunter.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\dea_hunter.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\cop2.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\cop_sergeant.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\cop_officer_ausbilder.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\cop_officer.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\cop_captain.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\civ_hatchback_sport.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\carbon_suv_V3.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\carbon_full_suv_v1.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Bayern1.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Batman_Hatch.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\barbie.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Autohaus.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Adidas_Abklatsch_Drache.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\Adidas_Abklatsch.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_offroad.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_logo.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_Hummingbird.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_hemett_02.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_hemett_01.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_02.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac_01.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\adac.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\30.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\zamak_front_justiz.jpg"];
	sleep 2.5;
	_tempPlakat setObjectTexture [0, "bambusfarm\Texturen\zamak_back-justiz.jpg"];
	sleep 2.5;
	deleteVehicle _tempPlakat;
};